        ('F-CB', 'Embark on a mystical journey, venturing into the heart of the unknown forest.', 'F1', 'F2B', FALSE), 
        ('F-CA', 'Seek guidance from the ancient whispers that rustle through the towering trees.', 'F1', 'F2A', FALSE), 
        ('F-CAA', 'Explore the sunlit trail, where the dappled light reveals the secrets of the enchanted woods.', 'F2A', 'F3AA' , FALSE), 
        ('F-CAB', 'Venture into the shadowed realm, where mysterious creatures lurk and ancient tales await discovery.', 'F2A', 'F3AB', FALSE), 
        ('F-CBA', 'Follow the moonlit path, navigating through the silvery glow that unveils the forest''s nocturnal wonders.', 'F2B', 'F3BA' , FALSE), 
        ('F-CBB', 'Enter the twilight passage, where the boundary between reality and enchantment becomes blurred.', 'F2B', 'F3BB' , FALSE), 
        ('F-CAAA', 'Befriend the luminous beings that inhabit the heart of the forest, their presence illuminating your path.', 'F3AA', 'F4X' , TRUE), 
        ('F-CAAB', 'Proceed with caution, but do not fear the unknown shadows that dance in the moonlight.', 'F3AA', 'F4Z', TRUE), 
        ('F-CABA', 'Confront the shadows with courage, unraveling the secrets hidden in the depths of the ancient woods.', 'F3AB', 'F4X' , TRUE), 
        ('F-CABB', 'Seek refuge in the twilight''s embrace, where the mystical aura shields you from the forest''s mysteries.', 'F3AB', 'F4Z' , TRUE), 
        ('F-CBAA', 'Join the moonlit revelry of the forest creatures, feeling the pulse of nature echoing through the night.', 'F3BA', 'F4X' , TRUE), 
        ('F-CBAB', 'Continue on your solitary journey, guided by the whispers of ancient trees that hold the forest''s secrets.', 'F3BA', 'F4Z', TRUE), 
        ('F-CBBA', 'Confront the unknown in the twilight, where the forest''s enchantment reaches its peak, revealing untold wonders.', 'F3BB', 'F4X' , TRUE), 
        ('F-CBBB', 'Retreat to the safety of shadows, where the mysterious tales of the forest remain veiled in a cloak of secrecy.', 'F3BB','F4Z' , TRUE);

-- OCEAN SETTING
        ('O-CB', 'Plunge into the abyss, where unknown depths beckon your curiosity.', 'O1', 'O2B', FALSE), 
        ('O-CA', 'Embark on a serene journey through sunlit waves, guided by gentle currents.', 'O1', 'O2A', FALSE), 
        ('O-CAA', 'Witness the elegance of sea creatures beneath the golden surface, as they dance in harmony.', 'O2A', 'O3AA', FALSE), 
        ('O-CAB', 'Explore the hidden shadows beneath the ocean''s surface, where enigmatic wonders await discovery.', 'O2A', 'O3AB', FALSE), 
        ('O-CBA', 'Immerse yourself in the tranquil glow of sunlit waters, where the surface reflects a world of serenity.', 'O2B', 'O3BA', FALSE), 
        ('O-CBB', 'Delve into the enigmatic depths where whispers echo mysteriously, revealing the secrets of the oceanic realm.', 'O2B', 'O3BB', FALSE), 
        ('O-CAAA', 'Navigate the sunlit waters with a heart full of curiosity, discovering the beauty hidden within the waves.', 'O3AA', 'O4X', TRUE), 
        ('O-CAAB', 'Proceed cautiously, mindful of the secrets concealed beneath the sunlit surface, awaiting revelation.', 'O3AA', 'O4Z', TRUE), 
        ('O-CABA', 'Embrace the harmonious dance within the sunlit waters, where every ripple tells a tale of tranquility.', 'O3AB', 'O4X', TRUE), 
        ('O-CABB', 'Uncover the mysterious whispers echoing from the shadows beneath, revealing the ocean''s concealed narratives.', 'O3AB', 'O4Z', TRUE), 
        ('O-CBAA', 'Dance amidst the tranquility of the sunlit waves, feeling the ebb and flow of the ocean''s rhythmic heartbeat.', 'O3BA', 'O4X', TRUE), 
        ('O-CBAB', 'Plunge into the depths guided by elusive whispers, exploring the ocean''s secrets that resonate below the surface.', 'O3BA', 'O4Z', TRUE), 
        ('O-CBBA', 'Float in the gentle embrace of the ocean''s tranquility, where each wave carries whispers of untold stories.', 'O3BB', 'O4X', TRUE), 
        ('O-CBBB', 'Explore the abyss where mysterious whispers resonate, revealing the hidden tales of the oceanic depths.', 'O3BB','O4Z', TRUE),
-- DESERT SETTING
        ('D-CB', 'Venture into the shifting sands of night, where secrets may be hidden beneath the cover of darkness.', 'D1', 'D2B', FALSE), 
        ('D-CA', 'Embark on a journey under the scorching day, where revelations may unfold under the blazing sun.', 'D1', 'D2A', FALSE), 
        ('D-CAA', 'Explore the mysteries concealed in the night''s embrace, guided by the hisses of the desert snake.', 'D2A', 'D3AA', FALSE), 
        ('D-CAB', 'Plunge into the shadows of the ever-changing night, where choices may reveal forgotten tales in the desert.', 'D2A', 'D3AB', FALSE), 
        ('D-CBA', 'Embrace the challenges presented by the relentless day, where the desert snake beckons you to weave your story.', 'D2B', 'D3BA', FALSE), 
        ('D-CBB', 'Navigate the day''s heat, seeking the oasis of choices beneath the azure sky and shifting sands.', 'D2B', 'D3BB', FALSE), 
        ('D-CAAA', 'Step into the eternal night, where choices may shape the destiny etched in the sands of time.', 'D3AA', 'D4X', TRUE), 
        ('D-CAAB', 'Proceed through the ever-shifting night cautiously, mindful of the secrets buried in the sands.', 'D3AA', 'D4Z', TRUE), 
        ('D-CABA', 'Journey through the perpetual day, where choices may become imprints in the sun-kissed desert sands.', 'D3AB', 'D4X', TRUE), 
        ('D-CABB', 'Uncover the whispers of the day, as choices echo through the shifting sands of the eternal desert.', 'D3AB', 'D4Z', TRUE), 
        ('D-CBAA', 'Stride through the relentless day, feeling the heartbeat of the desert beneath your choices.', 'D3BA', 'D4X', TRUE), 
        ('D-CBAB', 'Explore the day''s mysteries guided by the desert snake, revealing secrets etched in the sunlit sands.', 'D3BA', 'D4Z', TRUE), 
        ('D-CBBA', 'Wander through the eternal day, where choices may become an oasis in the vast desert of time.', 'D3BB', 'D4X', TRUE), 
        ('D-CBBB', 'Embark on a daylit exploration, where whispers of choices become tales in the ever-shifting desert.', 'D3BB','D4Z', TRUE),
-- CITY SETTING
        ('C-CA', 'Embark on a journey through the city''s secret cafes, where choices may unveil the stories etched in the rain-soaked streets.', 'C1', 'C2A', FALSE), 
        ('C-CB', 'Navigate the cyberpunk city alleys, where the old lady hints at choices revealing hidden secrets amidst neon-lit shadows.', 'C1', 'C2B', FALSE), 
        ('C-CAA', 'Explore the mysterious club hidden in the rain-drenched city, guided by the old lady''s whispers amidst the rhythmic downpour.', 'C2A', 'C3AA', FALSE), 
        ('C-CAB', 'Plunge into the city''s vibrant emporiums, where choices may lead you through the neon glow and secrets concealed in the pouring rain.', 'C2A', 'C3AB', FALSE), 
        ('C-CBA', 'Embrace the challenges presented by the crowded city streets, where the old lady beckons you to unravel its secrets.', 'C2B', 'C3BA', FALSE), 
        ('C-CBB', 'Navigate through the neon-lit rain, seeking hidden alleys and whispers amidst the city''s rhythmic storm.', 'C2B', 'C3BB', FALSE), 
        ('C-CAAA', 'Step into the city''s symphony, where choices may shape the destiny echoing through its vibrant streets.', 'C3AA', 'C4X', TRUE), 
        ('C-CAAB', 'Proceed through the city''s nightlife cautiously, mindful of the secrets concealed in its neon-lit embrace.', 'C3AA', 'C4Z', TRUE),
        ('C-CABA', 'Delve into the enigmatic stores concealed within the neon-lit alleys of the city.', 'C3AB', 'C4X', TRUE), 
        ('C-CABB', 'Explore the hidden corners of the city''s vibrant nightlife, where choices may lead to unexpected encounters.', 'C3AB', 'C4Z', TRUE),
        ('C-CBAA', 'Navigate the crowded streets and explore the vibrant city nightlife, where choices may reveal the city''s pulsating heart.', 'C3BA', 'C4X', TRUE), 
        ('C-CBAB', 'Follow the whispers in the city storm and uncover the hidden secrets within the neon-lit embrace.', 'C3BA', 'C4Z', TRUE),
        ('C-CBBA', 'Venture through the city''s alleys and rain-soaked streets, where choices may unlock the mysteries within its chaotic rhythm.', 'C3BB', 'C4X', TRUE),
        ('C-CBBB', 'Surrender to the whispers of the city storm, where choices may shape the destiny echoing through its vibrant streets.', 'C3BB', 'C4Z', TRUE);
-- SKY SETTING
        ('S-CB', 'Soar into the boundless expanse of unknown constellations, guided by an insatiable curiosity.', 'S1', 'S2B', FALSE), 
        ('S-CA', 'Embark on a serene journey through starlit realms, guided by the gentle currents of the celestial breeze.', 'S1', 'S2A', FALSE), 
        ('S-CAA', 'Witness the brilliance of celestial wonders, dancing in harmonious patterns across the cosmic canvas.', 'S2A', 'S3AA', FALSE), 
        ('S-CAB', 'Explore the concealed depths of the cosmic tapestry, where enigmatic constellations await your discovery.', 'S2A', 'S3AB', FALSE), 
        ('S-CBA', 'Immerse yourself in the tranquil glow of distant stars, reflecting dreams echoing through the celestial realm.', 'S2B', 'S3BA', FALSE), 
        ('S-CBB', 'Delve into the enigmatic depths of the cosmic expanse, where whispers echo mysteriously, revealing the secrets of the dream-laden sky.', 'S2B', 'S3BB', FALSE), 
        ('S-CAAA', 'Navigate the starlit realms with a heart full of curiosity, discovering the beauty hidden within the celestial symphony.', 'S3AA', 'S4X', TRUE), 
        ('S-CAAB', 'Proceed cautiously, mindful of secrets concealed within the cosmic tapestry, awaiting revelation.', 'S3AA', 'S4Z', TRUE), 
        ('S-CABA', 'Embrace the harmonious dance within the starlit realms, where every constellation tells a tale of tranquility.', 'S3AB', 'S4X', TRUE), 
        ('S-CABB', 'Uncover the mysterious whispers echoing from cosmic shadows, revealing concealed narratives within the dream-laden sky.', 'S3AB', 'S4Z', TRUE), 
        ('S-CBAA', 'Dance amidst the tranquility of distant stars, feeling the cosmic heartbeat resonating through the dream-laden sky.', 'S3BA', 'S4X', TRUE), 
        ('S-CBAB', 'Plunge into cosmic depths guided by elusive whispers, exploring celestial secrets resonating below the surface.', 'S3BA', 'S4Z', TRUE), 
        ('S-CBBA', 'Float in the gentle embrace of the dream-laden sky, where each constellation carries whispers of untold stories.', 'S3BB', 'S4X', TRUE), 
        ('S-CBBB', 'Explore the cosmic expanse where mysterious whispers resonate, revealing hidden tales within the dream-laden sky.', 'S3BB','S4Z', TRUE);